name: Mon premier workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install nodejs
        uses: actions/setup-node@v4
      - name: fetch repository
        uses: actions/checkout@v4
      - name: insall dependencies
        run: npm install
        working-directory: ./vite-project
