name: Mon premier workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: Configure cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-npm-${{ hashFiles('./vite-project/package.json') }}
          path: |
            ~/.npm
            ./vite-project/node_modules

      - name: Install dependencies
        run: npm install --prefer-offline
        working-directory: ./vite-project
